import next from "eslint-config-next";
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

// eslint-config-next 16 ships native flat config. The previous file wrapped the
// legacy shareable config in FlatCompat, which now resolves a self-referential
// object and crashes the run before a single file is linted.
const eslintConfig = [
  ...next,
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    // Generated by fumadocs-mdx on every build; linting it reports on code nobody wrote.
    ignores: [".source/**", ".next/**"],
  },
];

export default eslintConfig;
