// @ts-nocheck -- skip type checking
import * as docs_5 from "../content/docs/concepts/verification.mdx?collection=docs&hash=1784565116759"
import * as docs_4 from "../content/docs/concepts/credentials.mdx?collection=docs&hash=1784565116759"
import * as docs_3 from "../content/docs/guides/webhooks.mdx?collection=docs&hash=1784565116759"
import * as docs_2 from "../content/docs/quickstart.mdx?collection=docs&hash=1784565116759"
import * as docs_1 from "../content/docs/index.mdx?collection=docs&hash=1784565116759"
import * as docs_0 from "../content/docs/api.mdx?collection=docs&hash=1784565116759"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"api.mdx","absolutePath":"/Users/david/Projects/GLEMO/glemo-landing/content/docs/api.mdx"}, data: docs_0 }, { info: {"path":"index.mdx","absolutePath":"/Users/david/Projects/GLEMO/glemo-landing/content/docs/index.mdx"}, data: docs_1 }, { info: {"path":"quickstart.mdx","absolutePath":"/Users/david/Projects/GLEMO/glemo-landing/content/docs/quickstart.mdx"}, data: docs_2 }, { info: {"path":"guides/webhooks.mdx","absolutePath":"/Users/david/Projects/GLEMO/glemo-landing/content/docs/guides/webhooks.mdx"}, data: docs_3 }, { info: {"path":"concepts/credentials.mdx","absolutePath":"/Users/david/Projects/GLEMO/glemo-landing/content/docs/concepts/credentials.mdx"}, data: docs_4 }, { info: {"path":"concepts/verification.mdx","absolutePath":"/Users/david/Projects/GLEMO/glemo-landing/content/docs/concepts/verification.mdx"}, data: docs_5 }], [{"info":{"path":"meta.json","absolutePath":"/Users/david/Projects/GLEMO/glemo-landing/content/docs/meta.json"},"data":{"title":"Glemo","pages":["index","quickstart","api","---Understand---","concepts","guides","---Reference---","[API reference](/docs-reference)"]}}, {"info":{"path":"concepts/meta.json","absolutePath":"/Users/david/Projects/GLEMO/glemo-landing/content/docs/concepts/meta.json"},"data":{"title":"Concepts","pages":["credentials","verification"]}}, {"info":{"path":"guides/meta.json","absolutePath":"/Users/david/Projects/GLEMO/glemo-landing/content/docs/guides/meta.json"},"data":{"title":"Guides","pages":["webhooks"]}}])